### ISSUE TITLE
ESPHome 2024.10 and later

### ISSUE THREAD

**Issue by mSapik** [AdamKGoddard/XiaomiIR_ESPHome#11]
ESPHome 2024.10.0 introduced what turned out to be a breaking change for the type of ESP32 chip that is used in our ir remotes. See [the ESPHome changelog for more information](https://esphome.io/changelog/2024.10.0.html#esp32-advanced-mac-address-configuration)

And now i see error in log: `[D][esp-idf:000]: E (351954) system_api: Base MAC address from BLK0 of EFUSE CRC error, efuse_crc = 0xa7; calc_crc = 0xe6`

And now the device is not available in Home Assistant

**Comment by corvy** [comment]
Is this causing it to not connect to wifi? I have problems with a new device just flashed. Firmware is fine but not connecting to wifi even though it sees the ssid when scanning.

**Comment by corvy** [comment]
Just to be clearer about my error, if these are not related I can make another issue :)


```
[W][wifi_esp32:711]: Event: Disconnected ssid='NoT' bssid=F6:XX:XX:XX:XX:CD reason='4-Way Handshake Timeout'
[W][wifi:653]: Error while connecting to network.
[I][wifi:313]: WiFi Connecting to 'NoT'...
```

```
[D][esp-idf:000][wifi]: 
[W][wifi_esp32:711]: Event: Disconnected ssid='NoT' bssid=F6:XX:XX:XX:XX:79 reason='Unspecified'
[W][wifi:653]: Error while connecting to network.
[I][wifi:313]: WiFi Connecting to 'NoT'...
```

```
[D][esp-idf:000][wifi]: 
[W][wifi_esp32:711]: Event: Disconnected ssid='NoT' bssid=F6:XX:XX:XX:XX:79 reason='Auth Expired'
[W][wifi:653]: Error while connecting to network.
[I][wifi:313]: WiFi Connecting to 'NoT'...
```

I know my SSID password is correct, triple tested and hardcoded but it will not connect to wifi at all. 

Here is my full code for reference (no payload still, just trying to get it onto the wifi for now...):

<details open>
<summary>ESPHome Full code</summary>
<br>

```
esphome:
  name: ir-blaster-livingroom-esp32
  friendly_name: ir-blaster-livingroom-esp32
  platformio_options:
    extra_scripts: 
      - pre:/config/esphome/pre_extra_script.py

esp32:
  board: esp32doit-devkit-v1
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_FREERTOS_UNICORE: y
    advanced:
      ignore_efuse_mac_crc: true

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "ESP32 IR Fallback Hotspot"
    password: !secret hotspot_pw
    
# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret key
    
ota:
  platform: esphome
  password: !secret ota_pw

captive_portal:
  
web_server:
  port: 80
  auth:
    username: "ir-blaster"
    password: !secret hotspot_pw
  

remote_transmitter:
  pin:
    number: GPIO26
    inverted: True
  carrier_duty_percent: 50%
  id: xiaomi

```
</details>
